Fix one linked association so that it returns nil when the linked record does not exist.
Previously, I was getting "NoMethodError: undefined method `key' for nil:NilClass".  We can't assume the linked record will definitely be there since links don't act like foreign keys.  The linked record can be deleted.